USE [BD_CORPORATIVA_QA]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Sistema
-- Create date: 2026-01-15
-- Description:	Informe General Mensual - Horas Extras, Atrasos, Asistencia y Vacaciones
--              Calcula días a pagar en base a 30 días comerciales
--              Corrige suma de HE50, HE100 y Atraso considerando valores semanales
-- =============================================
ALTER PROCEDURE [dbo].[SP_RH_INFORME_GENERAL_MENSUAL]
(
	@GENCENCOS_ID	DECIMAL(10,0),  -- -1 para todos los centros de costo, o ID específico
	@PERIODO		VARCHAR(7)       -- Formato: 'YYYY-MM' (ejemplo: '2026-01')
)
AS
BEGIN
	SET NOCOUNT ON;

	-- Variables para manejo de fechas
	DECLARE @FECHA_INICIO DATE;
	DECLARE @FECHA_FIN DATE;
	DECLARE @DIAS_MES_COMERCIAL INT = 30; -- Base comercial de 30 días
	DECLARE @DIAS_MES_REAL INT;

	-- Calcular fechas del período
	SET @FECHA_INICIO = CAST(@PERIODO + '-01' AS DATE);
	SET @FECHA_FIN = EOMONTH(@FECHA_INICIO);
	SET @DIAS_MES_REAL = DAY(@FECHA_FIN);

	-- Si el centro de costo es 0, obtener todos los centros de costo
	IF @GENCENCOS_ID = 0
	BEGIN
		SELECT 
			-- Información básica del colaborador y empresa
			CC.GENCENCOS_DESCRIPCION AS 'Nombre_CECO',
			CC.GENCENCOS_CODIGO AS 'CECO',
			E.GENEMP_DESCRIPCION AS 'Empresa',
			CONVERT(VARCHAR(10), COL.RHCOL_RUT) + '-' + COL.RHCOL_DV AS 'RUN',
			RTRIM(LTRIM(ISNULL(COL.RHCOL_APEL_PATER, '') + ' ' + 
						ISNULL(COL.RHCOL_APEL_MATER, '') + ' ' + 
						ISNULL(COL.RHCOL_NOMBRE, ''))) AS 'NOMBRE',
			CG.RHCARGEN_DESCRIPCION AS 'Cargo',
			CON.RHCON_CONTRATO_NUMERO AS 'Contrato',
			CONVERT(VARCHAR(10),CON.RHCON_FECHA_INICIO,23) AS 'Fecha_Ingreso',
			
			-- Fecha de término (si existe)
			CONVERT(VARCHAR(10),CON.RHCON_FECHA_TERMINO,23) AS 'Fecha_Termino',
			
			-- Cálculo de días a pagar (base 30 días comerciales)
			CASE 
				WHEN CON.RHCON_FECHA_INICIO > @FECHA_INICIO THEN
					-- Si ingresó durante el mes: calcular proporción sobre 30 días
					CAST(
						(@DIAS_MES_COMERCIAL * 
						 (DATEDIFF(DAY, CON.RHCON_FECHA_INICIO, @FECHA_FIN) + 1) * 1.0 / 
						 @DIAS_MES_REAL) - 
						ISNULL((
							SELECT SUM(AC.RHASICON_DESCUENTO)
							FROM RH_ASISTENCIA A
							INNER JOIN RH_ASISTENCIA_CONCEPTO AC ON A.RHASICON_ID = AC.RHASICON_ID
							WHERE A.RHCOL_ID = COL.RHCOL_ID
							AND A.RHSIS_FECHA BETWEEN CON.RHCON_FECHA_INICIO AND @FECHA_FIN
							AND AC.RHASICON_DESCUENTO > 0
						), 0)
					AS DECIMAL(10,2))
				WHEN CON.RHCON_FECHA_TERMINO IS NOT NULL AND CON.RHCON_FECHA_TERMINO < @FECHA_FIN THEN
					-- Si terminó durante el mes: calcular proporción sobre 30 días
					CAST(
						(@DIAS_MES_COMERCIAL * 
						 (DATEDIFF(DAY, @FECHA_INICIO, CON.RHCON_FECHA_TERMINO) + 1) * 1.0 / 
						 @DIAS_MES_REAL) - 
						ISNULL((
							SELECT SUM(AC.RHASICON_DESCUENTO)
							FROM RH_ASISTENCIA A
							INNER JOIN RH_ASISTENCIA_CONCEPTO AC ON A.RHASICON_ID = AC.RHASICON_ID
							WHERE A.RHCOL_ID = COL.RHCOL_ID
							AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND CON.RHCON_FECHA_TERMINO
							AND AC.RHASICON_DESCUENTO > 0
						), 0)
					AS DECIMAL(10,2))
				ELSE
					-- Mes completo: base de 30 días comerciales
					CAST(
						@DIAS_MES_COMERCIAL - ISNULL((
							SELECT SUM(AC.RHASICON_DESCUENTO)
							FROM RH_ASISTENCIA A
							INNER JOIN RH_ASISTENCIA_CONCEPTO AC ON A.RHASICON_ID = AC.RHASICON_ID
							WHERE A.RHCOL_ID = COL.RHCOL_ID
							AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
							AND AC.RHASICON_DESCUENTO > 0
						), 0)
					AS DECIMAL(10,2))
			END AS 'Dias_A_Pagar',
			
			-- Horas Extras 50% (suma por semana, tomando un valor por semana)
			ISNULL((
				SELECT SUM(H50_Semanal)
				FROM (
					SELECT MAX(A.RHSIS_H50) AS H50_Semanal
					FROM RH_ASISTENCIA A
					LEFT JOIN GEN_FERIADO F ON A.RHSIS_FECHA = F.GENFER_FECHA AND F.GENFER_VIGENCIA = 'S'
					WHERE A.RHCOL_ID = COL.RHCOL_ID
					AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
					AND A.RHSIS_H50 IS NOT NULL
					AND A.RHSIS_H50 > 0
					AND DATEPART(WEEKDAY, A.RHSIS_FECHA) NOT IN (1, 7) -- Excluir domingo y sábado
					AND F.GENFER_ID IS NULL -- Excluir feriados
					GROUP BY DATEPART(YEAR, A.RHSIS_FECHA), DATEPART(ISO_WEEK, A.RHSIS_FECHA)
				) AS HE50_PorSemana
			), 0) AS 'HE50',
			
			-- Horas Extras 100% (suma por semana, tomando un valor por semana)
			ISNULL((
				SELECT SUM(H100_Semanal)
				FROM (
					SELECT MAX(A.RHSIS_H100) AS H100_Semanal
					FROM RH_ASISTENCIA A
					LEFT JOIN GEN_FERIADO F ON A.RHSIS_FECHA = F.GENFER_FECHA AND F.GENFER_VIGENCIA = 'S'
					WHERE A.RHCOL_ID = COL.RHCOL_ID
					AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
					AND A.RHSIS_H100 IS NOT NULL
					AND A.RHSIS_H100 > 0
					AND DATEPART(WEEKDAY, A.RHSIS_FECHA) NOT IN (1, 7) -- Excluir domingo y sábado
					AND F.GENFER_ID IS NULL -- Excluir feriados
					GROUP BY DATEPART(YEAR, A.RHSIS_FECHA), DATEPART(ISO_WEEK, A.RHSIS_FECHA)
				) AS HE100_PorSemana
			), 0) AS 'HE100',
			
			-- Atrasos (suma por semana, tomando un valor por semana)
			ISNULL((
				SELECT SUM(Atraso_Semanal)
				FROM (
					SELECT MAX(A.RHSIS_ATRASO) AS Atraso_Semanal
					FROM RH_ASISTENCIA A
					WHERE A.RHCOL_ID = COL.RHCOL_ID
					AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
					AND A.RHSIS_ATRASO IS NOT NULL
					AND A.RHSIS_ATRASO > 0
					AND DATEPART(WEEKDAY, A.RHSIS_FECHA) NOT IN (1, 7) -- Excluir fines de semana
					GROUP BY DATEPART(YEAR, A.RHSIS_FECHA), DATEPART(ISO_WEEK, A.RHSIS_FECHA)
				) AS Atraso_PorSemana
			), 0) AS 'Atraso',
			
			-- Licencias (LIC o LAC)
			ISNULL((
				SELECT COUNT(*)
				FROM RH_ASISTENCIA A
				INNER JOIN RH_ASISTENCIA_CONCEPTO AC ON A.RHASICON_ID = AC.RHASICON_ID
				WHERE A.RHCOL_ID = COL.RHCOL_ID
				AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
				AND AC.RHASICON_SIGLA IN ('LIC', 'LAC')
			), 0) AS 'Licencia',
			
			-- Vacaciones (excluyendo fines de semana y feriados)
			ISNULL((
				SELECT COUNT(*)
				FROM RH_ASISTENCIA A
				INNER JOIN RH_ASISTENCIA_CONCEPTO AC ON A.RHASICON_ID = AC.RHASICON_ID
				LEFT JOIN GEN_FERIADO F ON A.RHSIS_FECHA = F.GENFER_FECHA AND F.GENFER_VIGENCIA = 'S'
				WHERE A.RHCOL_ID = COL.RHCOL_ID
				AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
				AND AC.RHASICON_SIGLA = 'V'
				AND DATEPART(WEEKDAY, A.RHSIS_FECHA) NOT IN (1, 7) -- Excluir domingo y sábado
				AND F.GENFER_ID IS NULL -- Excluir feriados
			), 0) AS 'Vacaciones'
			
		FROM RH_COLABORADOR COL
		INNER JOIN RH_CONTRATO CON ON COL.RHCOL_ID = CON.RHCOL_ID
			AND COL.RHCOL_CONTRATO_ACTIVO = CON.RHCON_CONTRATO_NUMERO
		INNER JOIN GEN_CENTRO_COSTO CC ON CON.GENCENCOS_ID = CC.GENCENCOS_ID
		INNER JOIN GEN_EMPRESA E ON CC.GENEMP_ID = E.GENEMP_ID
		LEFT JOIN RH_CARGO_GENERICO CG ON CON.RHCARGEN_ID = CG.RHCARGEN_ID
		
		WHERE 
			-- El contrato debe estar activo durante el período
			(CON.RHCON_FECHA_INICIO <= @FECHA_FIN)
			AND (CON.RHCON_FECHA_TERMINO IS NULL OR CON.RHCON_FECHA_TERMINO >= @FECHA_INICIO)
			
		ORDER BY 
			CC.GENCENCOS_CODIGO,
			COL.RHCOL_RUT;
	END
	ELSE
	BEGIN
		-- Informe para un centro de costo específico
		SELECT 
			-- Información básica del colaborador y empresa
			CC.GENCENCOS_DESCRIPCION AS 'Nombre_CECO',
			CC.GENCENCOS_CODIGO AS 'CECO',
			E.GENEMP_DESCRIPCION AS 'Empresa',
			CONVERT(VARCHAR(10), COL.RHCOL_RUT) + '-' + COL.RHCOL_DV AS 'RUN',
			RTRIM(LTRIM(ISNULL(COL.RHCOL_APEL_PATER, '') + ' ' + 
						ISNULL(COL.RHCOL_APEL_MATER, '') + ' ' + 
						ISNULL(COL.RHCOL_NOMBRE, ''))) AS 'NOMBRE',
			CG.RHCARGEN_DESCRIPCION AS 'Cargo',
			CON.RHCON_CONTRATO_NUMERO AS 'Contrato',
			CONVERT(VARCHAR(10),CON.RHCON_FECHA_INICIO,23) AS 'Fecha_Ingreso',
			
			-- Fecha de término (si existe)
			CONVERT(VARCHAR(10),CON.RHCON_FECHA_TERMINO,23) AS 'Fecha_Termino',
			
			-- Cálculo de días a pagar (base 30 días comerciales)
			CASE 
				WHEN CON.RHCON_FECHA_INICIO > @FECHA_INICIO THEN
					-- Si ingresó durante el mes: calcular proporción sobre 30 días
					CAST(
						(@DIAS_MES_COMERCIAL * 
						 (DATEDIFF(DAY, CON.RHCON_FECHA_INICIO, @FECHA_FIN) + 1) * 1.0 / 
						 @DIAS_MES_REAL) - 
						ISNULL((
							SELECT SUM(AC.RHASICON_DESCUENTO)
							FROM RH_ASISTENCIA A
							INNER JOIN RH_ASISTENCIA_CONCEPTO AC ON A.RHASICON_ID = AC.RHASICON_ID
							WHERE A.RHCOL_ID = COL.RHCOL_ID
							AND A.RHSIS_FECHA BETWEEN CON.RHCON_FECHA_INICIO AND @FECHA_FIN
							AND AC.RHASICON_DESCUENTO > 0
						), 0)
					AS DECIMAL(10,2))
				WHEN CON.RHCON_FECHA_TERMINO IS NOT NULL AND CON.RHCON_FECHA_TERMINO < @FECHA_FIN THEN
					-- Si terminó durante el mes: calcular proporción sobre 30 días
					CAST(
						(@DIAS_MES_COMERCIAL * 
						 (DATEDIFF(DAY, @FECHA_INICIO, CON.RHCON_FECHA_TERMINO) + 1) * 1.0 / 
						 @DIAS_MES_REAL) - 
						ISNULL((
							SELECT SUM(AC.RHASICON_DESCUENTO)
							FROM RH_ASISTENCIA A
							INNER JOIN RH_ASISTENCIA_CONCEPTO AC ON A.RHASICON_ID = AC.RHASICON_ID
							WHERE A.RHCOL_ID = COL.RHCOL_ID
							AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND CON.RHCON_FECHA_TERMINO
							AND AC.RHASICON_DESCUENTO > 0
						), 0)
					AS DECIMAL(10,2))
				ELSE
					-- Mes completo: base de 30 días comerciales
					CAST(
						@DIAS_MES_COMERCIAL - ISNULL((
							SELECT SUM(AC.RHASICON_DESCUENTO)
							FROM RH_ASISTENCIA A
							INNER JOIN RH_ASISTENCIA_CONCEPTO AC ON A.RHASICON_ID = AC.RHASICON_ID
							WHERE A.RHCOL_ID = COL.RHCOL_ID
							AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
							AND AC.RHASICON_DESCUENTO > 0
						), 0)
					AS DECIMAL(10,2))
			END AS 'Dias_A_Pagar',
			
			-- Horas Extras 50% (suma por semana, tomando un valor por semana)
			ISNULL((
				SELECT SUM(H50_Semanal)
				FROM (
					SELECT MAX(A.RHSIS_H50) AS H50_Semanal
					FROM RH_ASISTENCIA A
					LEFT JOIN GEN_FERIADO F ON A.RHSIS_FECHA = F.GENFER_FECHA AND F.GENFER_VIGENCIA = 'S'
					WHERE A.RHCOL_ID = COL.RHCOL_ID
					AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
					AND A.RHSIS_H50 IS NOT NULL
					AND A.RHSIS_H50 > 0
					AND DATEPART(WEEKDAY, A.RHSIS_FECHA) NOT IN (1, 7) -- Excluir domingo y sábado
					AND F.GENFER_ID IS NULL -- Excluir feriados
					GROUP BY DATEPART(YEAR, A.RHSIS_FECHA), DATEPART(ISO_WEEK, A.RHSIS_FECHA)
				) AS HE50_PorSemana
			), 0) AS 'HE50',
			
			-- Horas Extras 100% (suma por semana, tomando un valor por semana)
			ISNULL((
				SELECT SUM(H100_Semanal)
				FROM (
					SELECT MAX(A.RHSIS_H100) AS H100_Semanal
					FROM RH_ASISTENCIA A
					LEFT JOIN GEN_FERIADO F ON A.RHSIS_FECHA = F.GENFER_FECHA AND F.GENFER_VIGENCIA = 'S'
					WHERE A.RHCOL_ID = COL.RHCOL_ID
					AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
					AND A.RHSIS_H100 IS NOT NULL
					AND A.RHSIS_H100 > 0
					AND DATEPART(WEEKDAY, A.RHSIS_FECHA) NOT IN (1, 7) -- Excluir domingo y sábado
					AND F.GENFER_ID IS NULL -- Excluir feriados
					GROUP BY DATEPART(YEAR, A.RHSIS_FECHA), DATEPART(ISO_WEEK, A.RHSIS_FECHA)
				) AS HE100_PorSemana
			), 0) AS 'HE100',
			
			-- Atrasos (suma por semana, tomando un valor por semana)
			ISNULL((
				SELECT SUM(Atraso_Semanal)
				FROM (
					SELECT MAX(A.RHSIS_ATRASO) AS Atraso_Semanal
					FROM RH_ASISTENCIA A
					WHERE A.RHCOL_ID = COL.RHCOL_ID
					AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
					AND A.RHSIS_ATRASO IS NOT NULL
					AND A.RHSIS_ATRASO > 0
					AND DATEPART(WEEKDAY, A.RHSIS_FECHA) NOT IN (1, 7) -- Excluir fines de semana
					GROUP BY DATEPART(YEAR, A.RHSIS_FECHA), DATEPART(ISO_WEEK, A.RHSIS_FECHA)
				) AS Atraso_PorSemana
			), 0) AS 'Atraso',
			
			-- Licencias (LIC o LAC)
			ISNULL((
				SELECT COUNT(*)
				FROM RH_ASISTENCIA A
				INNER JOIN RH_ASISTENCIA_CONCEPTO AC ON A.RHASICON_ID = AC.RHASICON_ID
				WHERE A.RHCOL_ID = COL.RHCOL_ID
				AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
				AND AC.RHASICON_SIGLA IN ('LIC', 'LAC')
			), 0) AS 'Licencia',
			
			-- Vacaciones (excluyendo fines de semana y feriados)
			ISNULL((
				SELECT COUNT(*)
				FROM RH_ASISTENCIA A
				INNER JOIN RH_ASISTENCIA_CONCEPTO AC ON A.RHASICON_ID = AC.RHASICON_ID
				LEFT JOIN GEN_FERIADO F ON A.RHSIS_FECHA = F.GENFER_FECHA AND F.GENFER_VIGENCIA = 'S'
				WHERE A.RHCOL_ID = COL.RHCOL_ID
				AND A.RHSIS_FECHA BETWEEN @FECHA_INICIO AND @FECHA_FIN
				AND AC.RHASICON_SIGLA = 'V'
				AND DATEPART(WEEKDAY, A.RHSIS_FECHA) NOT IN (1, 7) -- Excluir domingo y sábado
				AND F.GENFER_ID IS NULL -- Excluir feriados
			), 0) AS 'Vacaciones'
			
		FROM RH_COLABORADOR COL
		INNER JOIN RH_CONTRATO CON ON COL.RHCOL_ID = CON.RHCOL_ID
			AND COL.RHCOL_CONTRATO_ACTIVO = CON.RHCON_CONTRATO_NUMERO
		INNER JOIN GEN_CENTRO_COSTO CC ON CON.GENCENCOS_ID = CC.GENCENCOS_ID
		INNER JOIN GEN_EMPRESA E ON CC.GENEMP_ID = E.GENEMP_ID
		LEFT JOIN RH_CARGO_GENERICO CG ON CON.RHCARGEN_ID = CG.RHCARGEN_ID
		
		WHERE 
			-- Filtro por centro de costo específico
			CC.GENCENCOS_ID = @GENCENCOS_ID
			-- El contrato debe estar activo durante el período
			AND (CON.RHCON_FECHA_INICIO <= @FECHA_FIN)
			AND (CON.RHCON_FECHA_TERMINO IS NULL OR CON.RHCON_FECHA_TERMINO >= @FECHA_INICIO)
			
		ORDER BY 
			COL.RHCOL_RUT;
	END
END
GO
